### ISSUE TITLE
mts mimetype

### ISSUE THREAD

**Issue by benbro** [ninenines/cowlib#100]
.mts files are defined as <<"model">>, <<"vnd.mts">> in [cow_mimetypes](https://github.com/ninenines/cowlib/blob/master/src/cow_mimetypes.erl#L529)

I think it should be video/MP2T as shown in this [RFC](https://tools.ietf.org/html/rfc3555#section-4.2.9) and on [Wikipedia](https://en.wikipedia.org/wiki/.m2ts) on the table on the right. 

> The file extensions generally used with AVCHD are called .mts and .m2ts. Both MTS and .m2ts are based on MPEG 2 standards (which is a type of MPEG format).

**Comment by essen** [comment]
This is generated from the Apache list at https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types so if there's a problem with it you should see with them directly. You can always create your own function that overrides this value and then calls `all_ext`.

**Comment by benbro** [comment]
ok thanks.
