### ISSUE TITLE
Please remove the file ebin/cowlib.app, which prevent the 'make' operation from generating .beam files in ebin.

### ISSUE THREAD

**Issue by guzhangyu** [ninenines/cowlib#117]
I download the code, and execute the 'make -d' comannd. The console output tells me that it doesn't need to remake, because it is not newer than the ebin/cowlib.app file.
Then I delete the ebin/cowlib.app file and reexcute the 'make -d' command. This time it generates .beam files in ebin correctly.

**Comment by essen** [comment]
Yes it is unfortunate. The problem is that it is needed for rebar compatibility. When Cowlib is used as a dependency there is no problem as Erlang.mk automatically cleans. It is only when downloading manually that there is a problem. I'm open for a fix but removing the file is not the way to go.
