### ISSUE TITLE
Allow content-length in 204 reply 

### ISSUE THREAD

**Issue by Zert** [ninenines/cowlib#119]
Some servers are sending `content-length=0` header in the response with 204 code. Cowlib reset this connection with stream error: https://github.com/ninenines/cowlib/blob/master/src/cow_http2_machine.erl#L744
May be cowlib should handle `content-length` of 204 with value 0?

Similar issue in jdk: https://bugs.openjdk.java.net/browse/JDK-8218662

**Comment by essen** [comment]
The code you linked to is for HTTP/2. The related issue is for HTTP/1.1.

Please be more specific as to which server(s) you are having this issue with, as well as which protocol is impacted exactly.

**Comment by essen** [comment]
Yes because I need to know which servers are breaking the spec to know when I can remove the workaround again once it doesn't cause a problem anymore. But I am happy to receive further information when/if you get any and act on it.
