### ISSUE TITLE
Parse delta (integer) values of rfc5861 cache control headers

### ISSUE THREAD

**Issue by tanguilp** [ninenines/cowlib#121]
[rfc5861](https://datatracker.ietf.org/doc/html/rfc5861) defines the following headers:

- `stale-while-revalidate`
- `stale-if-error`

Currently `cow_http_hd:parse_cache_control/1` returns a binary for their value. Their delta values could be parsed like `max-age`, `max-stale`, `min-fresh` and `s-maxage` (here: https://github.com/ninenines/cowlib/blob/6deddc7d3360aa0f50eb2375cc0226157185c472/src/cow_http_hd.erl#L1170) and returned as integers as well.

**Comment by essen** [comment]
Closing in favor of the PR.
