### ISSUE TITLE
make tests fails, triq dependency seems to be missing

### ISSUE THREAD

**Issue by marianoguerra** [ninenines/cowlib#16]
tried also with make triq but fails with another error.

tried adding

    TEST_DEPS = triq
    dep_triq = ...

in the Makefile and running make deps but it didn't work

output (some output removed):

    make tests

     GEN    clean
     GEN    clean-app
     GEN    clean-ct
     ERLC   cow_multipart.erl cow_qs.erl cow_http_hd.erl cow_http.erl cow_spdy.erl cow_http_te.erl cow_date.erl cow_ws.erl cow_mimetypes.erl cow_cookie.erl
    src/cow_http_hd.erl:129: can't find include lib "triq/include/triq.hrl"
    src/cow_http_hd.erl:131: undefined macro 'LET/3'

    ...

    src/cow_http_hd.erl:2223: Warning: function range/0 is unused
    erlang.mk:257: recipe for target 'ebin/cowlib.app' failed
    make: *** [ebin/cowlib.app] Error 1

**Comment by essen** [comment]
I have added to Makefile:

```
TEST_DEPS = triq
dep_triq = git https://github.com/krestenkrab/triq master
```

But apparently forgot to commit.

**Comment by essen** [comment]
Oh and also `TEST_ERLC_OPTS += +'{parse_transform, eunit_autoexport}'`

I will fix that after I commit the current code.

**Comment by essen** [comment]
Should be good on the most recent commit. Thanks!
