### ISSUE TITLE
undefined parse transform 'horse_autoexport'

### ISSUE THREAD

**Issue by marianoguerra** [ninenines/cowlib#17]
clean clone, run make tests and get:

	 ERLC   cow_multipart.erl cow_qs.erl cow_http_hd.erl cow_http.erl cow_spdy.erl cow_http_te.erl cow_date.erl cow_ws.erl cow_mimetypes.erl cow_cookie.erl
	src/cow_multipart.erl: undefined parse transform 'horse_autoexport'
	erlang.mk:359: recipe for target 'ebin/cowlib.app' failed
	make[1]: *** [ebin/cowlib.app] Error 1
	erlang.mk:402: recipe for target 'test-build' failed
	make: *** [test-build] Error 2

**Comment by marianoguerra** [comment]
(all this is because I wan't to add a failing test for this case)

    13> cow_cookie:parse_cookie(<<"JSESSIONID=DE3F0006B859278F95210DECEAB68AC0; Path=/; HttpOnly">>). 
    {error,badarg}

it seems the parser doesn't handle the HttpOnly trailing field without an equal sign, it works if I add the equal sign or remove the HttpOnly field:

	14> cow_cookie:parse_cookie(<<"JSESSIONID=DE3F0006B859278F95210DECEAB68AC0; Path=/; HttpOnly=">>).
	[{<<"JSESSIONID">>,<<"DE3F0006B859278F95210DECEAB68AC0">>},
	 {<<"Path">>,<<"/">>},
	 {<<"HttpOnly">>,<<>>}]
	15> cow_cookie:parse_cookie(<<"JSESSIONID=DE3F0006B859278F95210DECEAB68AC0; Path=/;">>).          
	[{<<"JSESSIONID">>,<<"DE3F0006B859278F95210DECEAB68AC0">>},
	 {<<"Path">>,<<"/">>}]

**Comment by marianoguerra** [comment]
this one also fails: 

    <<"login=\"\"; Path=/; Secure; HttpOnly">>

**Comment by marianoguerra** [comment]
it seems the trailing HttpOnly without equal sign is something common, mochiweb_cookies.erl seems to do it:

    https://github.com/mochi/mochiweb/blob/master/src/mochiweb_cookies.erl#L105

and it can parse them:

	49> mochiweb_cookies:parse_cookie("userId=ff1b; Expires=Sun, 18-Nov-2046 17:38:56 GMT; Path=/; Secure; HttpOnly").                                
	[{"userId","ff1b"},
	 {"Expires","Sun"},
	 {"18-Nov-2046",[]},
	 {"Path",[]},
	 {"Secure",[]},
	 {"HttpOnly",[]}]
	50> mochiweb_cookies:parse_cookie("login=\"\"; Path=/; Secure; HttpOnly").                                        
	[{"login",[]},{"Path",[]},{"Secure",[]},{"HttpOnly",[]}]

**Comment by essen** [comment]
Test build issue noted, however you're on the wrong path there, parse_cookie is for parsing the *cookie* header, not *set-cookie*. The function to parse the *set-cookie* header is currently missing.

**Comment by essen** [comment]
Test build issue should now be fixed. Thanks!

As for cookies, I know this is missing so I am closing the ticket.
