### ISSUE TITLE
websockets error for iolist data

### ISSUE THREAD

**Issue by brigadier** [ninenines/cowlib#19]
It is Impossible to send anything but binary into websocket

this code doesn't work 
```
websocket_handle({text, Msg}, Req, State) ->
	Reply = ["a", "b"]
	{reply, {text, Reply}, Req, State};
```
because in `cow_ws` `payload_length` calculated by direct call of `byte_size` function

```
frame({text, Payload}, _) ->
	Len = payload_length(Payload),
	[<< 1:1, 0:3, 1:4, 0:1, Len/bits >>, Payload];
frame({binary, Payload}, _) ->
	Len = payload_length(Payload),
	[<< 1:1, 0:3, 2:4, 0:1, Len/bits >>, Payload].

payload_length(Payload) ->
	case byte_size(Payload) of
		N when N =< 125 -> << N:7 >>;
		N when N =< 16#ffff -> << 126:7, N:16 >>;
		N when N =< 16#7fffffffffffffff -> << 127:7, N:64 >>
	end.

```  

Maybe add an `iolist_to_binary` call for non-binary data?

**Comment by essen** [comment]
Yep though rather it should be an iolist_size call probably.

**Comment by essen** [comment]
Merged in master. Will make an 1.0.2 release with it next.

**Comment by essen** [comment]
Websocket code isn't in Cowlib 1.0.x so I did the change in Cowboy. Proceeding with Cowlib 1.0.2. Thanks!
