### ISSUE TITLE
Problems with multipart boundary generation

### ISSUE THREAD

**Issue by essen** [ninenines/cowlib#24]
Either `cow_multipart:boundary()` returns values that are incorrect, or `cow_http_hd:parse_content_type(Hd)` fails to parse valid headers (for example using multipart/form-data;boundary=Boundary, with Boundary including a slash).

More investigation needed, and the test for boundary creation should include parsing this header by cow_http_hd:parse_content_type since the header includes the boundary.

**Comment by maximk** [comment]
This is still an issue. As a workaround I stopped using base64:encode(crypto:rand_bytes(24)) for boundary generation as it may embed a slash.

**Comment by essen** [comment]
I have just pushed a fix for this. It now uses cow_base64url which implements the base64 algorithm of the same name. Enjoy!
