### ISSUE TITLE
windows build issues again on 1.3 

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [ninenines/cowlib#28]
Hi,

Please s it possible you apply similar updates as you did the last time to the Cowboy family of libs to avoid this windows build errors that seem to creep up in your newer builds.

Maybe if you use the updated erlang.mk file from the last time...

Regards.

**Comment by essen** [comment]
Can you point me to the previous fix?

**Comment by CharlesOkwuagwu** [comment]
arg.... it was in ranch...

**Comment by CharlesOkwuagwu** [comment]
https://github.com/ninenines/erlang.mk/issues/294#issuecomment-165184408

**Comment by essen** [comment]
Can you fork/clone Cowlib, run "make erlang-mk" and open a PR?

**Comment by CharlesOkwuagwu** [comment]
will try

**Comment by CharlesOkwuagwu** [comment]
which version? you went from 1.3 back to 1.0.2, the 1.0.2 works fine its the 1.3 that is the issue

**Comment by CharlesOkwuagwu** [comment]
Charles@PAPERLESS-ONE /d/github/cowlib
$ make erlang.mk
erlang.mk:68: *** Unable to detect platform. Please open a ticket with the output of uname -a..  Stop.

Charles@PAPERLESS-ONE /d/github/cowlib
$ uname -a
MINGW32_NT-6.2 PAPERLESS-ONE 1.0.18(0.48/3/2) 2012-11-21 22:34 i686 Msys

Charles@PAPERLESS-ONE /d/github/cowlib

**Comment by essen** [comment]
"make erlang-mk" not "erlang.mk" :-)

Though I probably should add it as an alias.

**Comment by CharlesOkwuagwu** [comment]
ahhh, ok

**Comment by CharlesOkwuagwu** [comment]
No such file:

Charles@PAPERLESS-ONE /d/github
$ cd cowlib/

Charles@PAPERLESS-ONE /d/github/cowlib
$ ls
AUTHORS  CHANGELOG.md  LICENSE  Makefile  README.md  circle.yml  ebin  erlang.mk  include  mintty.exe.stackdump  src

Charles@PAPERLESS-ONE /d/github/cowlib
$ make erlang-mk
erlang.mk:68: *** Unable to detect platform. Please open a ticket with the output of uname -a..  Stop.

Charles@PAPERLESS-ONE /d/github/cowlib
$

**Comment by essen** [comment]
Ah yeah of course. My bad. Will do it.

**Comment by essen** [comment]
Done. Please test and confirm it's fixed! Thanks!

**Comment by CharlesOkwuagwu** [comment]
Charles@PAPERLESS-ONE /d/github/cowlib
$ make erlang.mk
erlang.mk:4057: The variable OTP_DEPS is deprecated in favor of LOCAL_DEPS.
make: Nothing to be done for `erlang.mk'.

Charles@PAPERLESS-ONE /d/github/cowlib
$

**Comment by CharlesOkwuagwu** [comment]
I'm on Erlang version 18.2.1 ...

**Comment by CharlesOkwuagwu** [comment]
make: Nothing to be done for `erlang.mk'.

Charles@PAPERLESS-ONE /d/github/cowlib
$ make erlang-mk
erlang.mk:4057: The variable OTP_DEPS is deprecated in favor of LOCAL_DEPS.
git clone https://github.com/ninenines/erlang.mk .erlang.mk.build
Cloning into '.erlang.mk.build'...
remote: Counting objects: 5944, done.
remote: Total 5944 (delta 0), reused 0 (delta 0), pack-reused 5944R
Receiving objects: 100% (5944/5944), 2.87 MiB | 392.00 KiB/s, done.
Resolving deltas: 100% (3687/3687), done.
Checking connectivity... done.
if [ -f build.config ]; then cp build.config .erlang.mk.build/build.config; fi
make -C .erlang.mk.build
make[1]: Entering directory `/d/github/cowlib/.erlang.mk.build'
awk 'FNR==1 && NR!=1{print ""}1' core/core.mk index/*.mk core/index.mk core/deps.mk plugins/erlydtl.mk plugins/protobuffs.mk core/erlc.mk core/docs.mk core/rel.mk core/test.mk core/compat.mk plugins/asciidoc.mk plugins/bootstrap.mk plugins/c_src.mk plugins/ci.mk plugins/ct.mk plugins/dialyzer.mk plugins/edoc.mk plugins/escript.mk plugins/eunit.mk plugins/relx.mk plugins/shell.mk plugins/triq.mk plugins/xref.mk plugins/cover.mk \
                | sed 's/^ERLANG_MK_VERSION = .*/ERLANG_MK_VERSION = 2.0.0-pre.2-81-gbb6b947/' > erlang.mk
make[1]: Leaving directory `/d/github/cowlib/.erlang.mk.build'
cp .erlang.mk.build/erlang.mk ./erlang.mk
rm -rf .erlang.mk.build

Charles@PAPERLESS-ONE /d/github/cowlib

Works now

**Comment by essen** [comment]
Yeah I mean I did "make erlang-mk", you shouldn't have to do it anymore. It should work fine with current cowlib in your project.
