### ISSUE TITLE
cow_qs:qs can not have integer value?

### ISSUE THREAD

**Issue by dcy** [ninenines/cowlib#50]
Hi!
```cow_qs:qs([{<<"digit">>, 1}]). ``` will throw error:
```
** exception error: no function clause matching cow_qs:urlencode(1,<<"&digit=">>) (/home/dcy/hisir/epush/_build/default/lib/cowlib/src/cow_qs.erl, line 429)
     in function  cow_qs:qs/2 (/home/dcy/hisir/epush/_build/default/lib/cowlib/src/cow_qs.erl, line 183
```
Can't it have integer value?

**Comment by essen** [comment]
No.

**Comment by dcy** [comment]
Thanks

**Comment by essen** [comment]
For the reason: this function is the equivalent of the parsing function and echoes the same properties (query strings are key/value strings). A higher level function could take care of integers and others like you need.
