### ISSUE TITLE
crypto:rand_bytes/1 is deprecated

### ISSUE THREAD

**Issue by mspanc** [ninenines/cowlib#51]
While compiling cowlib on Erlang/OTP 19.2 I get the following warning:

```
src/cow_multipart.erl:392: Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
```

**Comment by essen** [comment]
Long fixed: https://github.com/ninenines/cowlib/commit/a7d5141d13c8944867c9361e544981d9954728c4
