### ISSUE TITLE
Chokes on (invalid) bodies that contain leading spaces

### ISSUE THREAD

**Issue by strange** [ninenines/cowlib#56]
I get the following crash when attempting to make a GET-request with gun to www.tripod.com:

    15:21:22.106 [error] CRASH REPORT Process <0.20289.10> with 0 neighbours crashed with reason: no function clause matching cow_http_te:chunked_len(<<" \r\n<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<HTML><HEAD>\n<TITLE>301 Moved Permanently...">>, 0, <<>>, 253) line 173

Code to reproduce:

    application:ensure_all_started(gun).

    {ok, ConnPid} = gun:open("www.tripod.com", 80).
    {ok, _Protocol} = gun:await_up(ConnPid).

    StreamRef = gun:get(ConnPid, "/").

    case gun:await(ConnPid, StreamRef) of
        {response, fin, _Status, _Headers} ->
                no_data;
        {response, nofin, _Status, _Headers} ->
                {ok, _Body} = gun:await_body(ConnPid, StreamRef);
        Other ->
                io:format("Other ~p~n", [Other])
    end.

The server identifies itself as "Squeegit/1.2.5 (3_sir)" which appears to be some AngelFire legacy server.

**Comment by essen** [comment]
On closer inspection it doesn't appear to be an invalid body. It's just that there's a space after the chunk size. And it's valid according to an errata for RFC7230.

**Comment by essen** [comment]
Done in the most recent commit. Your snippet above now works for me. Thanks!
