### ISSUE TITLE
src/cow_sse.erl:32: syntax error before: ':='

### ISSUE THREAD

**Issue by MatthiasLeeIBM** [ninenines/cowlib#57]
[Latest commit](https://github.com/ninenines/cowlib/commit/15750e632d9886eb9bfc876ba03402464b8facb3) on master causes compilation error:
```
src/cow_sse.erl:32: syntax error before: ':='
src/cow_sse.erl:44: type event() undefined
make[1]: *** [ebin/cowlib.app] Error 1
make: *** [app] Error 2
```

**Comment by essen** [comment]
It probably requires 19+.

**Comment by MatthiasLeeIBM** [comment]
ah ok, haven't move to 19 yet.

**Comment by essen** [comment]
Closing then. The intent is for the next tag to be 19+ and the next major version to support 19 and 20. Thanks!
