### ISSUE TITLE
compiling gives such error : cow_sse.erl:32: syntax error before: ':='

### ISSUE THREAD

**Issue by mbike2000ru** [ninenines/cowlib#58]
Compiling dependencies gives the following error:
 cow_sse.erl:32: syntax error before: ':='
 type event() undefined

**Comment by rslota** [comment]
+1, support for Erlang OTP other then 19+ is broken because of this spec.

**Comment by essen** [comment]
Yes the plans are to support 19+ in the next tag.

**Comment by mbike2000ru** [comment]
but how to compile in erlang 18 version?

**Comment by mbike2000ru** [comment]
we can not upgrade to 19+

**Comment by essen** [comment]
Then don't follow master? I don't see a problem here. This is new functionality tied to Gun/Cowboy versions that will require 19+.

**Comment by mbike2000ru** [comment]
cowboy takes cowlib master during dependency- compiling, so I can not change it

**Comment by essen** [comment]
Cowboy 2.0 requires 19+. It's only an accident if it works with 18 currently. :-)

**Comment by mbike2000ru** [comment]
==> cowboy (get-deps)
Pulling cowlib from {git,"https://github.com/ninenines/cowlib","master"}
Cloning into 'cowlib'...
==> cowlib (get-deps)

**Comment by mbike2000ru** [comment]
then how to tell cowboy to pull another branch (not master)?

**Comment by mbike2000ru** [comment]
here is my rebar.conf:

{sub_dirs, ["apps/acceptor", "rel"]}.
{deps,
  [{lager, ".*", {git, "https://github.com/basho/lager.git"}, "HEAD"},
  {ranch, ".*", {git, "https://github.com/ninenines/ranch.git", "master"}},
  {epgsql, ".*", {git, "https://github.com/epgsql/epgsql.git"}, "HEAD"},
  {gproc, ".*", {git, "https://github.com/uwiger/gproc.git"}, "master"},
  {sync, ".*", {git, "https://github.com/rustyio/sync.git", {branch, "master"}}},
  {eredis, ".*", {git, "https://github.com/wooga/eredis.git", "HEAD"}},
  {cowboy, ".*", {git, "https://github.com/ninenines/cowboy.git", "dbb636034f20736e16eb9d6c809217c9525b6cbd"}},
  {jsx, ".*", {git, "https://github.com/talentdeficit/jsx.git", "HEAD"}},
  {gen_smtp, ".*", {git, "https://github.com/Vagabond/gen_smtp.git", "HEAD"}},
  {hackney, ".*", {git, "https://github.com/benoitc/hackney.git", "HEAD"}}

  ]}.

**Comment by essen** [comment]
Add cowlib to your dependencies and it'll override Cowboy's.
