### ISSUE TITLE
sec-websocket-protocol values are case insensitive

### ISSUE THREAD

**Issue by randysecrist** [ninenines/cowlib#60]
According to this document, https://ninenines.eu/docs/en/cowboy/1.0/manual/cowboy_req/

The values for the header ```sec-websocket-protocol``` are case sensitive.  However I am noticing that after parsing the header using cowboy_req, the value is coming back lower case.

Relevant bits of code are here:

https://github.com/ninenines/cowlib/blob/master/src/cow_http_hd.erl#L2626-L2627
https://github.com/ninenines/cowlib/blob/master/src/cow_http_hd.erl#L3382-L3392

I suspect this is a bug, but not 100% sure.  I'm looking for the spec and clarification that tells me if the values for ```sec-websocket-protocol``` should be sensitive or not.

**Comment by essen** [comment]
I haven't fixed it yet.

**Comment by essen** [comment]
Done locally, pushing later today. Thanks!
