### ISSUE TITLE
Using compression for websockets fails because of zlib:zstream() not being a port anymore in OTP 20

### ISSUE THREAD

**Issue by jfacorro** [ninenines/cowlib#62]
The call to `erlang:port_connect/2` [here](https://github.com/ninenines/cowlib/blob/2.0.0/src/cow_ws.erl#L156) fails with `badarg` for OTP 20.1.1. This makes the `cowboy_websocket` to return a 400 [here](https://github.com/ninenines/cowboy/blob/master/src/cowboy_websocket.erl#L105), but without any hint of what the problem is (in this case a 500 might be more appropriate?).

I pinged the author of the change in `zilb` [here](https://github.com/erlang/otp/commit/948ee9b34f34a55cb4b70b7077a849c7dc7a5f18#commitcomment-24834567), because I couldn't find a workaround to the current situation.

**Comment by essen** [comment]
Thanks. I'm guilty of not having double checked Websocket compression with OTP 20.1. :-)

**Comment by essen** [comment]
It's probably worth opening a bug on bugs.erlang.org FYI.

**Comment by jfacorro** [comment]
I opened [this](https://bugs.erlang.org/browse/ERL-494) issue in bug.erlang.org.

Thank you for all your work!

**Comment by essen** [comment]
`zlib:set_controlling_process/2` was added in OTP 20.1.3.

**Comment by essen** [comment]
This should be fixed in most recent Cowlib (2.0.1) and Cowboy (master).
