### ISSUE TITLE
http status 308

### ISSUE THREAD

**Issue by leoliu** [ninenines/cowlib#65]
Bump into this today:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308

**Comment by essen** [comment]
Yes I am aware, didn't know I didn't add it though.

**Comment by essen** [comment]
I got this done locally but I need more time to do a Cowlib release so that'll have to wait next week.

**Comment by essen** [comment]
Closing because this is added locally and I'm pushing later today with a new cowlib release. Thanks!
