### ISSUE TITLE
The authorization scheme for HTTP Basic Authentication should not be case sensitive

### ISSUE THREAD

**Issue by bipthelin** [ninenines/cowlib#84]
The `cowboy_req:parse_header(<<"authorization">>, Req)` code in Cowboy uses `cow_http_hd:parse_authorization/1`. The code doesn't compare case insensitive which as far as I can understand breaks [RFC 2617](http://tools.ietf.org/html/rfc2617#section-1.2). Both `Basic`, `basic` and other cases should be considered valid.

The code in question: https://github.com/ninenines/cowlib/blob/master/src/cow_http_hd.erl#L891

**Comment by bipthelin** [comment]
I've made a PR for this problem #85

**Comment by essen** [comment]
Thanks!
